# Generated by Django 4.2.1 on 2023-05-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('backup_domain', models.CharField(max_length=255)),
                ('force_update', models.CharField(max_length=255)),
                ('need_update', models.CharField(max_length=255)),
                ('normal_update_link', models.CharField(max_length=255)),
                ('deep_update_link', models.CharField(max_length=255)),
            ],
        ),
    ]
