# Generated by Django 4.2.1 on 2023-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='force_update',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=1),
        ),
        migrations.AlterField(
            model_name='config',
            name='need_update',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=1),
        ),
    ]
