# Generated by Django 4.2.1 on 2023-05-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0003_alter_config_backup_domain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='deep_update_link',
            new_name='deep_download_link',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='normal_update_link',
            new_name='normal_download_link',
        ),
        migrations.RemoveField(
            model_name='config',
            name='force_update',
        ),
        migrations.RemoveField(
            model_name='config',
            name='need_update',
        ),
        migrations.AddField(
            model_name='config',
            name='current_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='last_accepted_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='CoreApp.config')),
            ],
        ),
    ]
